services:
  ############################################################
  ############################################################
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: pylambdatasks-lambda
    ports:
      - "9000:8080"
    networks:
      - pylambdatasks-net

    environment:
      - PYLAMBDATASKS_DEBUG=0

    entrypoint: ""
    command:
     - "pylambdatasks"
     - "run"
     - "handler:app"
     - "--reload"
     - "--host"
     - "0.0.0.0"
     - "--port"
     - "8080"
    volumes:
      - ./develop:/var/task
      - ./src/pylambdatasks:/var/task/pylambdatasks


  ############################################################
  ############################################################
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: pylambdatasks-api
    ports:
      - "8000:8000"
    networks:
      - pylambdatasks-net

    environment:
      - PYLAMBDATASKS_DEBUG=0

    entrypoint: ""
    command: uvicorn api:api --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./develop:/var/task
      - ./src/pylambdatasks:/var/task/pylambdatasks
    depends_on:
      - lambda

networks:
  pylambdatasks-net:
    driver: bridge
